### ISSUE TITLE
Patch com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-0

### ISSUE THREAD

**Issue by ihortom** [snowplow/iglu-central#673] opened 2017-12-01 19:26 UTC
We have come across a scenario when a device can produce no `carrier` resulting in `null` sent down the pipeline. Could we host an updated version of `mobile_context` with a relaxed restriction?

The changes required

```
"carrier": {
    "type": ["string", "null"]
}
```

No changes to SQL and jsonpaths.

**Comment by alexanderdean** [comment] 2017-12-01 21:34
Thanks @ihortom , can you open the PR please?

**Comment by alexanderdean** [comment] 2017-12-14 11:14
Duplicate of #674

**Comment by alexanderdean** [comment] 2018-01-16 23:23
Whoops, re-opening

**Closed** 2018-01-19 08:16 UTC
Labels: patch-schema
