### ISSUE TITLE
Add com.mailgun/recipient_unsubscribed/jsonschema/1-0-0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#658] opened 2017-10-27 09:59 UTC

**Comment by knservis** [comment] 2017-10-31 14:54
Duplicate of #542

**Closed by knservis** 2017-10-31 14:54 UTC
Labels: new-schema

**Comment by BenFradet** [comment] 2017-10-31 14:57
@knservis When closing an issue like this one, it's necessary to unschedule it by removing the milestone :+1:
